// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SiTaG_API.Data;

#nullable disable

namespace SiTaG_API.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20240219232137_UpdatingAnimal")]
    partial class UpdatingAnimal
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("SiTaG_API.Entities.Animals", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<decimal>("BirthWeight")
                        .HasColumnType("decimal(65,30)");

                    b.Property<string>("Color")
                        .IsRequired()
                        .HasColumnType("varchar(50)");

                    b.Property<decimal>("CurrentWeight")
                        .HasColumnType("decimal(65,30)");

                    b.Property<DateTime>("DateOfBirth")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<int?>("Id_Father")
                        .HasColumnType("int");

                    b.Property<int?>("Id_Mother")
                        .HasColumnType("int");

                    b.Property<int>("Id_Race")
                        .HasColumnType("int");

                    b.Property<int>("Id_status")
                        .HasColumnType("int");

                    b.Property<string>("Identifier")
                        .IsRequired()
                        .HasColumnType("varchar(5)");

                    b.Property<DateTime>("LastUpdate")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Name")
                        .HasColumnType("varchar(50)");

                    b.Property<int>("Sex")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("Id_Father");

                    b.HasIndex("Id_Mother");

                    b.ToTable("Animals");
                });

            modelBuilder.Entity("SiTaG_API.Entities.Animals", b =>
                {
                    b.HasOne("SiTaG_API.Entities.Animals", "Father")
                        .WithMany()
                        .HasForeignKey("Id_Father");

                    b.HasOne("SiTaG_API.Entities.Animals", "Mother")
                        .WithMany()
                        .HasForeignKey("Id_Mother");

                    b.Navigation("Father");

                    b.Navigation("Mother");
                });
#pragma warning restore 612, 618
        }
    }
}
